export const actions = {
  ADD_NEW_SUBMISSION: '[submission] ADD_NEW_SUBMISSION',

  FETCH_BY_DATE_REQUESTED: '[submission] FETCH_BY_DATE_REQUESTED',
  FETCH_BY_USER_REQUESTED: '[submission] FETCH_BY_USER_REQUESTED',
  FETCH_SUBMISSIONS_LIST_PENDING: '[submission] FETCH_SUBMISSIONS_LIST_PENDING',
  FETCH_SUBMISSIONS_LIST_SUCCESS: '[submission] FETCH_SUBMISSIONS_LIST_SUCCESS',
  FETCH_SUBMISSIONS_LIST_FAIL: '[submission] FETCH_SUBMISSIONS_LIST_FAIL',

  ADD_TO_QUERY_HISTORY: '[submission] ADD_TO_QUERY_HISTORY',
  SET_SUBMISSIONS_QUERY: '[submission] SET_SUBMISSIONS_QUERY',
  SET_CURRENT_PAGE: '[submission] SET_PAGE',
  SET_SUBMISSIONS_PER_PAGE: '[submission] SET_SUBMISSIONS_PER_PAGE'

}

export const query = {
  LIST_DEFAULT: {
    offset: 0,
    limit: 5,
  },
  // TODO: change to 10/20/30 later
  LIMIT_OPTIONS: [5, 10, 20]
}

