export const actions = {
  LOG_USER_IN: '[user] LOG_USER_IN',
  LOG_USER_OUT: '[user] LOG_USER_OUT',

  FETCH_LEADERBOARD_REQUEST: '[user] FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: '[user] FETCH_USERS_SUCCESS',
  FETCH_USERS_FAIL: '[user] FETCH_USERS_FAIL',
  
  FETCH_ELIMINATED_REQUEST: '[user] FETCH_ELIMINATED_REQUEST', 
  FETCH_ELIMINATED_SUCCESS: '[user] FETCH_ELIMINATED_SUCCESS',
  FETCH_ELIMINATED_FAIL: '[user] FETCH_ELIMINATED_FAIL',

  
  // FETCH_USER_PENDING: '[user] FETCH_USER_PENDING',
  // FETCH_USER_SUCCESS: '[user] FETCH_USER_SUCCESS',
  // FETCH_USER_FAIL: '[user] FETCH_USER_FAIL'
}


